spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: patient-service
            uri: lb://PATIENT-SERVICE
            predicates:
              - Path=/patients/**
            filters:
              - RewritePath=/patients/?(?<segment>.*), /$\{segment}
          - id: doctor-service
            uri: lb://DOCTOR-SERVICE
            predicates:
              - Path=/doctors/**
            filters:
              - RewritePath=/doctors/?(?<segment>.*), /$\{segment}
          - id: appointment-service
            uri: lb://APPOINTMENT-SERVICE
            predicates:
              - Path=/appointments/**
            filters:
              - RewritePath=/appointments/?(?<segment>.*), /$\{segment}
  application:
    name: api-gateway
eureka:
  client:
    register-with-server: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
server:
  port: 0


